### ISSUE TITLE
GitHub Actions flow

### ISSUE THREAD

**Issue by jahpola** [tvv-lippu-ja-maksujarjestelma-oy/waltti-apc#245]
Currently we have codeql, trivy action and main ci/cd action flow. Upcoming dependabot automation depends on branch protection rules. 

1. Vision a CI flow from source to docker hub
2. Vision a CD flow from docker hub to Kubernetes

Needs a flowchart, basic tests etc

**Comment by haphut** [comment]
## Happy path:

Always pull latest `edge` tag into `dev` environment.
Run e2e tests in `dev`.

Pull the latest service versions that passed e2e tests in `dev` environment into `stage` environment, for example every Wednesday morning at 09:00 local time.
In `stage` manifests, use `sha-*` tags instead of `edge`, though.

In `stage` and `prod`, monitor:

1. log message counts of Pulsar clients for different error levels
1. message rates of different Pulsar topics
1. Pulsar topic storage usage
1. cloud resource consumption

If `stage` or `prod` has problems according to monitoring, notify developers.

If `stage` has not had problems for e.g. a week, manually copy `stage` image versions into `prod` and update manifest repo tag`prod`.


## Unhappy path

Our services should survive if external services go down.

If we write broken logic, before reaching `prod` the logic has to survive:

1. CI tests, e.g. type checking, linting and unit tests,
1. e2e tests in `dev`,
1. e.g. a week in `stage` without tripping alarms.

If the broken logic breaks the data flow so that a downstream microservice chokes on broken messages it consumes from Pulsar, in `dev` and `stage` it is probably easiest to fix the logic bug and forcefully empty the relevant Pulsar topics with broken messages.

If the broken logic reaches `prod`, we might need to fix the downstream service with a kludge.
